engines:
  coverage:
    exclude_paths:
      - 'Examples/**/*'
      - '*.md'
  remark-lint:
    exclude_paths:
      - fastlane/README.md
exclude_paths:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - 'fastlane/**/*'
  - 'Package.*'
  - '*.yml'
  - '*.xcodeproj/**/*'
  - '*.xcworkspace/**/*'
  - '*.plist'
  - '*.podspec'
