name: Vulnerability scan
on:
  push:
    branches:
      - snyk-integration-test
      - master
      - main

jobs:
  security:
    runs-on:
      group: macos-gh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"
      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master
      - name: Run Snyk monitor for vulnerabilities
        run: snyk monitor --org=sdk --file=Package.swift
        env: 
          SNYK_TOKEN: ${{ secrets.SNYK_SDK_TOKEN }}
