name: Vulnerability scan
 on:
   push:
     branches:
       - snyk-integration-test
       - master
       - main

 jobs:
   security:
     runs-on: 
       group: macos-gh
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Run Snyk monitor for vulnerabilities
         uses: snyk/actions/gradle@master
         env: 
           SNYK_TOKEN: ${{ secrets.SNYK_SDK_TOKEN }}
         with:
           command: monitor
           args: --org=sdk --all-sub-project
